kind: Namespace
apiVersion: v1
metadata:
  name: identity
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: keycloak-config
  namespace: identity
data:
  PROXY_ADDRESS_FORWARDING: "true"
  DB_VENDOR: "mssql"
  DB_ADDR: "keycloak-sqlserver.database.windows.net"
  DB_DATABASE: "Keycloak"
  DB_USER: "KeycloakAdmin"
  DB_PASSWORD: "2021@Keycl0@k"
  DB_PORT: "1433"

  # KEYCLOAK_USER: admin
  # KEYCLOAK_PASSWORD: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak-deployment
  name: keycloak-deployment
  namespace: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: keycloak-deployment
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:15.0.2
          resources:
            limits:
              memory: "1Gi"
              cpu: "800m"
            requests:
              memory: "1Gi"
              cpu: "800m"
          envFrom:
            - configMapRef:
                name: keycloak-config
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak-hpa
  namespace: identity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keycloak-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75
---
apiVersion: v1
kind: Service
metadata:
  namespace: identity
  name: keycloak-service
spec:
  selector:
    app: keycloak-deployment
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
  namespace: identity
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - keycloak.limateixeira.site
      secretName: keycloak-tls
  rules:
    - host: keycloak.limateixeira.site
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: keycloak-service
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: jailton.junior94@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
